### ISSUE TITLE
Brainstorming, real-time, together at some point?

### ISSUE THREAD

**Issue by faddat** [Xe/hive#2]
You've got fresh ideas in clustering.  I *think* I do.  I'd really like to do a hangouts chat or whatever (collaborative mind map?) and see what concepets we share and try to plot out a direction for the whole crazy p2p, microservices, distributed application, micro-server (referring to its physical size) revolution-ish currently sweeping through our servers like wildfire.  

You in?

**Comment by Xe** [comment]
If you have Telegram, I am [@miamorecadenza](https://telegram.me/miamorecadenza).

**Comment by faddat** [comment]
Finally got it installed. Migratory lifestyle with many phone numbers eats apps like this for lunch.
